#!/usr/bin/env bash
# configures an Nginx server so that /redirect_me redirects to another page.
# the redirection is configured as a "301 Moved Permanently"

apt-get update
apt-get install -y nginx

echo "Hello World!" > /var/www/html/index.html
printf %s "server {
	listen 80;
	listen [::]:80 default_server;
	root   /var/www/html;
	index  index.html index.htm;

	location /redirect_me {
		return 301 https://github.com/Kwagmire;
	}
}" > /etc/nginx/sites-available/default

service nginx restart
